### ISSUE TITLE
When pressing Esc, TypeError is thrown

### ISSUE THREAD

**Issue by web-padawan** [PolymerElements/paper-radio-group#72] opened 2016-12-26 11:59 UTC
### Description

When pressing `Esc` key, the error is thrown:
```
Uncaught TypeError: Cannot read property 'blur' of undefined
    at HTMLElement._onEscKey (iron-menu-behavior.html:344)
    at HTMLElement._triggerKeyHandler (iron-a11y-keys-behavior.html:489)
    at HTMLElement._onKeyBindingEvent (iron-a11y-keys-behavior.html:473)
```

In Firefox is looks like this:

```
TypeError: this.focusedItem is undefined
```
### Expected outcome

No error should be thrown

### Actual outcome

Error is thrown each time Esc is being pressed. 
Pressing one of arrow keys seems to prevent further Esc hits to cause this error. 

### Steps to reproduce

1. Go to https://beta.webcomponents.org/element/PolymerElements/paper-radio-group/demo/demo/index.html
2. Focus one of the `paper-radio-group`
3. Press Esc

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9

**Comment by notwaldorf** [comment] 2017-01-05 00:55
I think that's a problem with the catalog, where 'esc' is trying to close the Demo overlay, and not a bug with `paper-radio-group`. Here's a jsbin where `esc` does nothing (nor throws an error): http://output.jsbin.com/nehiraj

Tentatively closing this, but cc'ing @samuelli to take a look at the catalog code

**Closed by notwaldorf** 2017-01-05 00:55 UTC

**Comment by dman777** [comment] 2018-06-03 20:48
Polymer 1.... I am hitting this error also in my own app with iron-menu-behavior and paper-radio-group. There is also a overlay involved. How was this resolved?
