### ISSUE TITLE
paper-radio-button nested in custom element goes unnoticed

### ISSUE THREAD

**Issue by truefusion** [PolymerElements/paper-radio-group#65] opened 2016-08-05 13:47 UTC
### Problem

I have a paper-radio-button nested within a custom element.  I expected the button to be picked up by paper-radio-group, but it was not caught. I've been able to narrow it down to the call to queryDistributedElements() in _updateItems() of the IronSelectableBehavior (https://github.com/PolymerElements/iron-selector/blob/master/iron-selectable.html#L272). Changing queryDistributedElements() to querySelectorAll() would quickly solve the issue, but I know IronSelectableBehavior is used in more than one place and that might have undesirable effects.

I have made a custom element mimicking paper-radio-group, applying the aforementioned solution to its _updateItems() method, and it works.

### Live Demo

https://jsfiddle.net/vbkpmat4/

As you can see, the third item is not considered part of the list.

### Browsers Affected
All.

**Comment by notwaldorf** [comment] 2016-08-05 22:46
Yeah, unfortunately this is a known limitation of iron-selector: https://github.com/PolymerElements/iron-selector/issues/42

Closing this as a duplicate of that issue.

**Closed by notwaldorf** 2016-08-05 22:46 UTC
